<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSources\Content;

use Atlas\Table\Table;

/**
 * @method ContentRow|null fetchRow($primaryVal)
 * @method ContentRow[] fetchRows(array $primaryVals)
 * @method ContentTableSelect select(array $whereEquals = [])
 * @method ContentRow newRow(array $cols = [])
 * @method ContentRow newSelectedRow(array $cols)
 */
class ContentTable extends Table
{
    const DRIVER = 'sqlsrv';

    const NAME = 'content';

    const COLUMNS = [
        'row_id' => array (
  'name' => 'row_id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'insrted_at' => array (
  'name' => 'insrted_at',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'updated_at' => array (
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'title' => array (
  'name' => 'title',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'content' => array (
  'name' => 'content',
  'type' => 'varchar',
  'size' => -1,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'author' => array (
  'name' => 'author',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'draft' => array (
  'name' => 'draft',
  'type' => 'bit',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => '1',
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'parent' => array (
  'name' => 'parent',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'row_id',
        'insrted_at',
        'updated_at',
        'title',
        'content',
        'author',
        'draft',
        'parent',
    ];

    const COLUMN_DEFAULTS = [
        'row_id' => null,
        'insrted_at' => null,
        'updated_at' => null,
        'title' => null,
        'content' => null,
        'author' => null,
        'draft' => '1',
        'parent' => null,
    ];

    const PRIMARY_KEY = [
        'row_id',
    ];

    const AUTOINC_COLUMN = 'row_id';

    const AUTOINC_SEQUENCE = null;
}
