<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Server\Models\Sysdiagrams;

use Atlas\Table\Row;

/**
 * @property mixed $name nvarchar(128) NOT NULL
 * @property mixed $principal_id int(10,0) NOT NULL
 * @property mixed $diagram_id int(10,0) NOT NULL
 * @property mixed $version int(10,0)
 * @property mixed $definition varbinary(-1)
 */
class SysdiagramsRow extends Row
{
    protected $cols = [
        'name' => null,
        'principal_id' => null,
        'diagram_id' => null,
        'version' => null,
        'definition' => null,
    ];
}
