<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSources\ContentsCateogire;

/**
 * @property mixed $row_id int(10,0) NOT NULL
 * @property mixed $insrted_at datetime NOT NULL
 * @property mixed $updated_at datetime NOT NULL
 * @property mixed $content int(10,0) NOT NULL
 * @property mixed $categorie int(10,0) NOT NULL
 */
trait ContentsCateogireFields
{
}
