<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Server\Models\Log;

use Atlas\Table\Row;

/**
 * @property mixed $row_id int(10,0) NOT NULL
 * @property mixed $inserted_at datetime NOT NULL
 * @property mixed $updated_at datetime NOT NULL
 * @property mixed $author_id int(10,0) NOT NULL
 * @property mixed $model varchar(255) NOT NULL
 * @property mixed $idstr int(10,0) NOT NULL
 * @property mixed $previous_value text(65535) NOT NULL
 * @property mixed $new_value text(65535) NOT NULL
 */
class LogRow extends Row
{
    protected $cols = [
        'row_id' => null,
        'inserted_at' => null,
        'updated_at' => null,
        'author_id' => null,
        'model' => null,
        'idstr' => null,
        'previous_value' => null,
        'new_value' => null,
    ];
}
