<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Server\Models\ContentsCategory;

/**
 * @property mixed $row_id int(10,0) NOT NULL
 * @property mixed $inserted_at datetime NOT NULL
 * @property mixed $updated_at datetime NOT NULL
 * @property mixed $content_id int(10,0) NOT NULL
 * @property mixed $categorie_id int(10,0) NOT NULL
 */
trait ContentsCategoryFields
{
}
