<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace App\DataSources\User;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class UserTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'row_id',
            'insrted_at',
            'updated_at',
            'email',
            'first_name',
            'last_name',
            'hashed_password',
            'rgpd',
            'newsletter',
            'role',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'row_id' => (object) array (
  'name' => 'row_id',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
),
            'insrted_at' => (object) array (
  'name' => 'insrted_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'updated_at' => (object) array (
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'email' => (object) array (
  'name' => 'email',
  'type' => 'varchar',
  'size' => '255',
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'first_name' => (object) array (
  'name' => 'first_name',
  'type' => 'varchar',
  'size' => '255',
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'last_name' => (object) array (
  'name' => 'last_name',
  'type' => 'varchar',
  'size' => '255',
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'hashed_password' => (object) array (
  'name' => 'hashed_password',
  'type' => 'varchar',
  'size' => '500',
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'rgpd' => (object) array (
  'name' => 'rgpd',
  'type' => 'bit',
  'size' => '1',
  'scale' => NULL,
  'notnull' => true,
  'default' => '((0))',
  'autoinc' => false,
  'primary' => false,
),
            'newsletter' => (object) array (
  'name' => 'newsletter',
  'type' => 'bit',
  'size' => '1',
  'scale' => NULL,
  'notnull' => true,
  'default' => '((0))',
  'autoinc' => false,
  'primary' => false,
),
            'role' => (object) array (
  'name' => 'role',
  'type' => 'tinyint',
  'size' => '3',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'row_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'row_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'row_id' => null,
            'insrted_at' => '(getdate())',
            'updated_at' => '(getdate())',
            'email' => null,
            'first_name' => null,
            'last_name' => null,
            'hashed_password' => null,
            'rgpd' => '((0))',
            'newsletter' => '((0))',
            'role' => null,
        ];
    }
}
