<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace App\DataSources\Translation;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class TranslationTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'translation';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'row_id',
            'insrted_at',
            'updated_at',
            'lang',
            'key',
            'value',
            'author',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'row_id' => (object) array (
  'name' => 'row_id',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
),
            'insrted_at' => (object) array (
  'name' => 'insrted_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'updated_at' => (object) array (
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'lang' => (object) array (
  'name' => 'lang',
  'type' => 'varchar',
  'size' => '10',
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'key' => (object) array (
  'name' => 'key',
  'type' => 'varchar',
  'size' => '500',
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'value' => (object) array (
  'name' => 'value',
  'type' => 'nchar',
  'size' => '10',
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'author' => (object) array (
  'name' => 'author',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'row_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'row_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'row_id' => null,
            'insrted_at' => '(getdate())',
            'updated_at' => '(getdate())',
            'lang' => null,
            'key' => null,
            'value' => null,
            'author' => null,
        ];
    }
}
