<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Datasources\Translation;

use Atlas\Table\Row;

/**
 * @property mixed $row_id int(10,0) NOT NULL
 * @property mixed $insrted_at datetime NOT NULL
 * @property mixed $updated_at datetime NOT NULL
 * @property mixed $lang varchar(10) NOT NULL
 * @property mixed $key varchar(500) NOT NULL
 * @property mixed $value nchar(10) NOT NULL
 * @property mixed $author int(10,0) NOT NULL
 */
class TranslationRow extends Row
{
    protected $cols = [
        'row_id' => null,
        'insrted_at' => null,
        'updated_at' => null,
        'lang' => null,
        'key' => null,
        'value' => null,
        'author' => null,
    ];
}
