<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Server\Models\Translation;

use Atlas\Table\Table;

/**
 * @method TranslationRow|null fetchRow($primaryVal)
 * @method TranslationRow[] fetchRows(array $primaryVals)
 * @method TranslationTableSelect select(array $whereEquals = [])
 * @method TranslationRow newRow(array $cols = [])
 * @method TranslationRow newSelectedRow(array $cols)
 */
class TranslationTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'translation';

    const COLUMNS = [
        'row_id' => [
            'name' => 'row_id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'inserted_at' => [
            'name' => 'inserted_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'updated_at' => [
            'name' => 'updated_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'lang' => [
            'name' => 'lang',
            'type' => 'varchar',
            'size' => 45,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'key' => [
            'name' => 'key',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'value' => [
            'name' => 'value',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'author' => [
            'name' => 'author',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'row_id',
        'inserted_at',
        'updated_at',
        'lang',
        'key',
        'value',
        'author',
    ];

    const COLUMN_DEFAULTS = [
        'row_id' => null,
        'inserted_at' => null,
        'updated_at' => null,
        'lang' => null,
        'key' => null,
        'value' => null,
        'author' => null,
    ];

    const PRIMARY_KEY = [
        'row_id',
    ];

    const AUTOINC_COLUMN = 'row_id';

    const AUTOINC_SEQUENCE = null;
}
