-- MySQL Script generated by MySQL Workbench
-- jeu. 08 nov. 2018 12:15:40 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atlas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `atlas` ;

-- -----------------------------------------------------
-- Schema atlas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atlas` DEFAULT CHARACTER SET latin1 ;
USE `atlas` ;

-- -----------------------------------------------------
-- Table `atlas`.`content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atlas`.`content` ;

CREATE TABLE IF NOT EXISTS `atlas`.`content` (
  `row_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inserted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `author_id` INT(11) NULL DEFAULT NULL,
  `draft` BIT(1) NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`row_id`),
  UNIQUE INDEX `row_id_UNIQUE` (`row_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `atlas`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atlas`.`user` ;

CREATE TABLE IF NOT EXISTS `atlas`.`user` (
  `row_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inserted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `birth_place` VARCHAR(255) NULL DEFAULT NULL,
  `birth_day` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `hashed_password` VARCHAR(255) NOT NULL,
  `rgpd` BIT(1) NOT NULL,
  `newsletter` BIT(1) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`row_id`),
  UNIQUE INDEX `row_id_UNIQUE` (`row_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `atlas`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atlas`.`categorie` ;

CREATE TABLE IF NOT EXISTS `atlas`.`categorie` (
  `row_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inserted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `author_id` INT(11) NOT NULL,
  PRIMARY KEY (`row_id`),
  UNIQUE INDEX `row_id_UNIQUE` (`row_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `atlas`.`contents_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atlas`.`contents_categories` ;

CREATE TABLE IF NOT EXISTS `atlas`.`contents_categories` (
  `row_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inserted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `content_id` INT(11) NOT NULL,
  `categorie_id` INT(11) NOT NULL,
  PRIMARY KEY (`row_id`),
  UNIQUE INDEX `row_id_UNIQUE` (`row_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `atlas`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atlas`.`log` ;

CREATE TABLE IF NOT EXISTS `atlas`.`log` (
  `row_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inserted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `author_id` INT(11) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `idstr` INT(11) NOT NULL,
  `previous_value` TEXT NOT NULL,
  `new_value` TEXT NOT NULL,
  PRIMARY KEY (`row_id`),
  UNIQUE INDEX `row_id_UNIQUE` (`row_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `atlas`.`translation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atlas`.`translation` ;

CREATE TABLE IF NOT EXISTS `atlas`.`translation` (
  `row_id` INT(11) NOT NULL AUTO_INCREMENT,
  `inserted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lang` VARCHAR(45) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `value` TEXT NOT NULL,
  `author` INT(11) NOT NULL,
  PRIMARY KEY (`row_id`),
  UNIQUE INDEX `row_id_UNIQUE` (`row_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
