<?php declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: marc
 * Date: 17/11/18
 * Time: 13:31
 */

namespace App\Ipolitic\Nawpcore\Components;

class FieldView extends View
{
    public $states = [
        "message"           => "",
        "value"             => "",
        "column"            => "",
        "placeHolder"       => "",
        "icon"              => "",
        "autoCompletionUrl" => "",
        "humanField"        => "",
    ];

    public function render(): string
    {
        $this->states["humanField"] = str_replace("_", " ", $this->states["column"]);
        $this->states["humanField"] = ucfirst($this->states["humanField"]);
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
