<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace App\DataSources\Log;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class LogTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'log';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'row_id',
            'insrted_at',
            'updated_at',
            'author',
            'model',
            'id',
            'previous_value',
            'new_value',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'row_id' => (object) array (
  'name' => 'row_id',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
),
            'insrted_at' => (object) array (
  'name' => 'insrted_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'updated_at' => (object) array (
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'author' => (object) array (
  'name' => 'author',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'model' => (object) array (
  'name' => 'model',
  'type' => 'varchar',
  'size' => '255',
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'id' => (object) array (
  'name' => 'id',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'previous_value' => (object) array (
  'name' => 'previous_value',
  'type' => 'text',
  'size' => '2147483647',
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'new_value' => (object) array (
  'name' => 'new_value',
  'type' => 'text',
  'size' => '2147483647',
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'row_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'row_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'row_id' => null,
            'insrted_at' => '(getdate())',
            'updated_at' => '(getdate())',
            'author' => null,
            'model' => null,
            'id' => null,
            'previous_value' => null,
            'new_value' => null,
        ];
    }
}
