<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Datasources\Log;

use Atlas\Table\Table;

/**
 * @method LogRow|null fetchRow($primaryVal)
 * @method LogRow[] fetchRows(array $primaryVals)
 * @method LogTableSelect select(array $whereEquals = [])
 * @method LogRow newRow(array $cols = [])
 * @method LogRow newSelectedRow(array $cols)
 */
class LogTable extends Table
{
    const DRIVER = 'sqlsrv';

    const NAME = 'log';

    const COLUMNS = [
        'row_id' => array(
  'name' => 'row_id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => true,
  'primary' => true,
  'options' => null,
),
        'insrted_at' => array(
  'name' => 'insrted_at',
  'type' => 'datetime',
  'size' => null,
  'scale' => null,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'updated_at' => array(
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => null,
  'scale' => null,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'author' => array(
  'name' => 'author',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'model' => array(
  'name' => 'model',
  'type' => 'varchar',
  'size' => 255,
  'scale' => null,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'id' => array(
  'name' => 'id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'previous_value' => array(
  'name' => 'previous_value',
  'type' => 'varchar',
  'size' => -1,
  'scale' => null,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
        'new_value' => array(
  'name' => 'new_value',
  'type' => 'varchar',
  'size' => -1,
  'scale' => null,
  'notnull' => true,
  'default' => null,
  'autoinc' => false,
  'primary' => false,
  'options' => null,
),
    ];

    const COLUMN_NAMES = [
        'row_id',
        'insrted_at',
        'updated_at',
        'author',
        'model',
        'id',
        'previous_value',
        'new_value',
    ];

    const COLUMN_DEFAULTS = [
        'row_id' => null,
        'insrted_at' => null,
        'updated_at' => null,
        'author' => null,
        'model' => null,
        'id' => null,
        'previous_value' => null,
        'new_value' => null,
    ];

    const PRIMARY_KEY = [
        'row_id',
    ];

    const AUTOINC_COLUMN = 'row_id';

    const AUTOINC_SEQUENCE = null;
}
