<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace App\DataSources\ContentsCategories;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ContentsCategoriesTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'contents_categories';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'row_id',
            'insrted_at',
            'updated_at',
            'content',
            'categorie',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'row_id' => (object) array (
  'name' => 'row_id',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
),
            'insrted_at' => (object) array (
  'name' => 'insrted_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'updated_at' => (object) array (
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => '23',
  'scale' => '3',
  'notnull' => true,
  'default' => '(getdate())',
  'autoinc' => false,
  'primary' => false,
),
            'content' => (object) array (
  'name' => 'content',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'categorie' => (object) array (
  'name' => 'categorie',
  'type' => 'int',
  'size' => '10',
  'scale' => '0',
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'row_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'row_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'row_id' => null,
            'insrted_at' => '(getdate())',
            'updated_at' => '(getdate())',
            'content' => null,
            'categorie' => null,
        ];
    }
}
