<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Datasources\Categorie;

use Atlas\Table\Table;

/**
 * @method CategorieRow|null fetchRow($primaryVal)
 * @method CategorieRow[] fetchRows(array $primaryVals)
 * @method CategorieTableSelect select(array $whereEquals = [])
 * @method CategorieRow newRow(array $cols = [])
 * @method CategorieRow newSelectedRow(array $cols)
 */
class CategorieTable extends Table
{
    const DRIVER = 'sqlsrv';

    const NAME = 'categorie';

    const COLUMNS = [
        'row_id' => array (
  'name' => 'row_id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'inserted_at' => array (
  'name' => 'inserted_at',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'updated_at' => array (
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'title' => array (
  'name' => 'title',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'content' => array (
  'name' => 'content',
  'type' => 'varchar',
  'size' => -1,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'parent' => array (
  'name' => 'parent',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'author' => array (
  'name' => 'author',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'row_id',
        'inserted_at',
        'updated_at',
        'title',
        'content',
        'parent',
        'author',
    ];

    const COLUMN_DEFAULTS = [
        'row_id' => null,
        'inserted_at' => null,
        'updated_at' => null,
        'title' => null,
        'content' => null,
        'parent' => null,
        'author' => null,
    ];

    const PRIMARY_KEY = [
        'row_id',
    ];

    const AUTOINC_COLUMN = 'row_id';

    const AUTOINC_SEQUENCE = null;
}
