<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Datasources\ContentsCategory;

/**
 * @property mixed $row_id int(10,0) NOT NULL
 * @property mixed $inserted_at datetime NOT NULL
 * @property mixed $updated_at datetime NOT NULL
 * @property mixed $content int(10,0) NOT NULL
 * @property mixed $categorie int(10,0) NOT NULL
 * @property null|false|\App\Datasources\Content\ContentRecord $[content]
 * @property null|false|\App\Datasources\Categorie\CategorieRecord $[categorie]
 */
trait ContentsCategoryFields
{
}
