<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSources\Translation;

use Atlas\Table\Table;

/**
 * @method TranslationRow|null fetchRow($primaryVal)
 * @method TranslationRow[] fetchRows(array $primaryVals)
 * @method TranslationTableSelect select(array $whereEquals = [])
 * @method TranslationRow newRow(array $cols = [])
 * @method TranslationRow newSelectedRow(array $cols)
 */
class TranslationTable extends Table
{
    const DRIVER = 'sqlsrv';

    const NAME = 'translation';

    const COLUMNS = [
        'row_id' => array (
  'name' => 'row_id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'insrted_at' => array (
  'name' => 'insrted_at',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'updated_at' => array (
  'name' => 'updated_at',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'lang' => array (
  'name' => 'lang',
  'type' => 'varchar',
  'size' => 10,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'key' => array (
  'name' => 'key',
  'type' => 'varchar',
  'size' => 500,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'value' => array (
  'name' => 'value',
  'type' => 'nchar',
  'size' => 10,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'author' => array (
  'name' => 'author',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'row_id',
        'insrted_at',
        'updated_at',
        'lang',
        'key',
        'value',
        'author',
    ];

    const COLUMN_DEFAULTS = [
        'row_id' => null,
        'insrted_at' => null,
        'updated_at' => null,
        'lang' => null,
        'key' => null,
        'value' => null,
        'author' => null,
    ];

    const PRIMARY_KEY = [
        'row_id',
    ];

    const AUTOINC_COLUMN = 'row_id';

    const AUTOINC_SEQUENCE = null;
}
